/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: [
      'scontent.cdninstagram.com',
      'scontent-nrt1-1.cdninstagram.com',
      'scontent-nrt2-2.cdninstagram.com',
      'scontent-lax3-2.cdninstagram.com',
      'scontent-iad3-1.cdninstagram.com',
      'scontent-iad3-2.cdninstagram.com',
      'scontent.xx.fbcdn.net',
      'instagram.com',
      'scontent-nrt1-2.cdninstagram.com',
      'scontent-nrt2-1.cdninstagram.com',
      'scontent-lax3-1.cdninstagram.com',
      'scontent-lax3-3.cdninstagram.com',
      'scontent-iad3-3.cdninstagram.com',
      'scontent.cdninstagram.com',
      'cdninstagram.com',
      'fbcdn.net',
      'scontent.fkix2-1.fna.fbcdn.net',
      'scontent.fkix1-1.fna.fbcdn.net',
      'scontent.xx.fbcdn.net',
      'scontent.cdninstagram.com',
      'scontent-ort2-2.cdninstagram.com',
      'scontent-ort2-1.cdninstagram.com',
      'scontent-mxp1-1.cdninstagram.com',
      'scontent-mxp1-2.cdninstagram.com',
      'scontent-mad1-1.cdninstagram.com',
      'scontent-mad1-2.cdninstagram.com',
      'scontent-lhr8-1.cdninstagram.com',
      'scontent-lhr8-2.cdninstagram.com',
      'scontent-ams4-1.cdninstagram.com',
      'scontent-ams4-2.cdninstagram.com',
      'scontent.cdninstagram.com',
      'instagram.fkix2-1.fna.fbcdn.net',
      'instagram.fkix1-1.fna.fbcdn.net',
      'instagram.fkix2-2.fna.fbcdn.net',
      'instagram.fkix1-2.fna.fbcdn.net',
      'instagram.fbkk22-1.fna.fbcdn.net',
      'instagram.fbkk22-2.fna.fbcdn.net',
      'instagram.fbkk23-1.fna.fbcdn.net',
      'instagram.fbkk23-2.fna.fbcdn.net',
      'instagram.com',
      'www.instagram.com',
    ],
  },
}

module.exports = nextConfig
