name: Trigger Vercel Rebuild

on:
  schedule:
    - cron: '18 18 * * *'  # UTC 18:18 → JST 03:18（+9時間）
  workflow_dispatch:
jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Webhook
        run: |
          curl -sf -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
